# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    git checkout master
    git status
    ls -alt
    git config --global user.name 'Amir-Azure'
    git config --global user.email 'amir.hosseinzadeh@echontech.com.tr'

    #git remote add github https://github.com/AmirHome/patients_v2.git
    #cat .git/config
    #git branch
    #git checkout -b master
    
    #git pull https://amir.email%40yahoo.com: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@github.com/AmirHome/patients_v2.git

    git push https://amir.email%40yahoo.com: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@github.com/AmirHome/patients_v2.git HEAD:master
    #git push -u github master