# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |  # Multi-line script for clarity
    git --version
    #git config --global user.name 'AmirHome'  # Replace with your username
    #git config --global user.email 'amir.email@yahoo.com'  # Replace with your email
    # git remote add backup https://<backup_url>.git  # Replace with your backup remote URL
    #git push backup --mirror  # Push all branches to backup remote
