services:
  
  #PHP Service
  app:
    build:
      args:
        user: deploy
        uid: 1000
      context: ./deploy/docker/bin/${PHPVERSION}
      # dockerfile: Dockerfile
    image: deploy/php
    container_name: app
    restart: unless-stopped
    tty: true
    # environment:
    #   SERVICE_NAME: app
    #   SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www/admin
      - ../chat:/var/www/chat
      - ./deploy/docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db

  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/admin
      - ../chat/public:/var/www/chat
      - ./deploy/docker/config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./deploy/docker/logs/nginx:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - app

  #MySQL Service
  db:
    build:
      context: "./deploy/docker/bin/${DATABASE}"
    container_name: "${DATABASE}"
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./deploy/docker/config/mysql/my.cnf:/etc/mysql/my.cnf
      - ${MYSQL_DATA_DIR-./deploy/docker/data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./deploy/docker/logs/mysql}:/var/log/mysql
    networks:
      - app-network
    command: --skip-grant-tables

#Docker Networks
networks:
  app-network:
    driver: bridge
