services:
  
  #PHP Service
  app:
    build:
      args:
        user: deploy
        uid: 1000
      context: ./deploy/docker/bin/${PHPVERSION}
      # dockerfile: Dockerfile
    image: deploy/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./deploy/docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./deploy/docker/config/nginx/conf.d/:/etc/nginx/conf.d/
      # - ./deploy/docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/docker/logs/nginx:/var/log/nginx
    networks:
      - app-network

  #MySQL Service
  db:
    build:
      context: "./deploy/docker/bin/${DATABASE}"
    container_name: "${DATABASE}"
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ${MYSQL_INITDB_DIR-./deploy/docker/config/initdb}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./deploy/docker/data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./deploy/docker/logs/mysql}:/var/log/mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local